# numpy 的聚合运算

In [1]:
import numpy as np

In [3]:
L=np.random.random(100)
L

array([0.60889796, 0.01389773, 0.6855958 , 0.72487144, 0.70136388,
       0.3151211 , 0.74617493, 0.25289353, 0.57829117, 0.97437636,
       0.65819651, 0.6525973 , 0.66637241, 0.69504953, 0.25192373,
       0.32705238, 0.29330913, 0.34160791, 0.06424668, 0.77399128,
       0.37111836, 0.55635711, 0.01303019, 0.10246622, 0.2759256 ,
       0.74724082, 0.43706096, 0.91706137, 0.60644729, 0.22447664,
       0.09067921, 0.00962467, 0.41950811, 0.69657597, 0.55085878,
       0.16176331, 0.82442323, 0.69110142, 0.81454239, 0.44914408,
       0.59458398, 0.65738848, 0.17212546, 0.62629038, 0.10710365,
       0.17307482, 0.01966642, 0.82477516, 0.12050347, 0.55312753,
       0.27562719, 0.7806516 , 0.92945834, 0.86820186, 0.3825558 ,
       0.70254203, 0.41915947, 0.95176719, 0.62035455, 0.30399467,
       0.85419237, 0.17075168, 0.34773421, 0.94886512, 0.30079232,
       0.03808392, 0.47262791, 0.49629013, 0.55204063, 0.47996659,
       0.34445707, 0.95163875, 0.04681718, 0.87227232, 0.25920

In [4]:
sum(L)

47.367349541302076

In [5]:
np.sum(L)

47.36734954130208

In [6]:
big_array=np.random.rand(1000000)

In [7]:
%timeit sum(big_array)

146 ms ± 1.92 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%timeit np.sum(big_array)

1.28 ms ± 30.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
np.min(big_array)

1.7991479279722e-06

In [10]:
np.max(big_array)

0.999999939775959

In [11]:
big_array.min()

1.7991479279722e-06

In [12]:
big_array.max()

0.999999939775959

In [13]:
X=np.arange(16).reshape(4,-1)

In [14]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
np.sum(X)

120

In [16]:
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [17]:
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [18]:
np.prod(X)

0

In [19]:
np.prod(X+1)

2004189184

In [20]:
np.mean(X)

7.5

In [21]:
L=np.array([1,2,2,10])

In [22]:
np.mean(L)

3.75

In [23]:
np.median(L)

2.0

In [24]:
np.percentile(big_array,q=50)

0.4996386035230163

In [25]:
np.mean(big_array)

0.49992631498765805

In [26]:
np.median(big_array)

0.4996386035230163

In [27]:
np.percentile(big_array,q=100)

0.999999939775959

In [28]:
np.max(big_array)

0.999999939775959

In [32]:
for percent in [0,25,50,75,100]:
    print(np.percentile(big_array,q=percent))

1.7991479279722e-06
0.2502668393637667
0.4996386035230163
0.7496438508655887
0.999999939775959


In [33]:
np.var(big_array)

0.08329040663272197

In [34]:
np.std(big_array)

0.28860077379092725

In [35]:
x=np.random.normal(0,1,size=100000)

In [36]:
np.mean(x)

-0.006567062120162499

In [37]:
np.std(x)

1.0028359791445063

## 索引

In [38]:
np.min(x)

-4.005366493878409

In [39]:
np.argmin(x)

19042

In [40]:
x[19042]

-4.005366493878409

In [41]:
np.argmax(x)

76222

In [42]:
x[76222]

4.242775175011054

In [43]:
np.max(x)

4.242775175011054

## 排序和使用索引

In [44]:
X=np.arange(16)

In [45]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [46]:
np.random.shuffle(X)

In [47]:
X

array([11,  6, 14,  8,  9,  7, 12, 15,  1, 10, 13,  4,  5,  0,  3,  2])

In [48]:
np.sort(X)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
X

array([11,  6, 14,  8,  9,  7, 12, 15,  1, 10, 13,  4,  5,  0,  3,  2])

In [50]:
X.sort()

In [51]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
X=np.random.randint(10,size=(4,4))

In [53]:
X

array([[2, 5, 8, 6],
       [4, 0, 4, 8],
       [8, 2, 7, 4],
       [3, 1, 9, 6]])

In [54]:
np.sort(X)

array([[2, 5, 6, 8],
       [0, 4, 4, 8],
       [2, 4, 7, 8],
       [1, 3, 6, 9]])

In [56]:
np.sort(X,axis=1)

array([[2, 5, 6, 8],
       [0, 4, 4, 8],
       [2, 4, 7, 8],
       [1, 3, 6, 9]])

In [58]:
np.sort(X,axis=0)

array([[2, 0, 4, 4],
       [3, 1, 7, 6],
       [4, 2, 8, 6],
       [8, 5, 9, 8]])

In [55]:
x=np.arange(16)

In [59]:
np.random.shuffle(x)

In [60]:
x

array([10,  4,  1,  8, 12,  6,  5, 15,  2, 11,  7,  3,  9,  0, 14, 13])

In [61]:
np.argsort(x)

array([13,  2,  8, 11,  1,  6,  5, 10,  3, 12,  0,  9,  4, 15, 14,  7],
      dtype=int32)

In [62]:
np.partition(x,3)

array([ 0,  1,  2,  3,  4,  5, 10,  6, 12, 11,  7,  8,  9, 13, 14, 15])

In [63]:
np.argpartition(x,3)

array([13,  2,  8, 11,  1,  6,  0,  5,  4,  9, 10,  3, 12, 15, 14,  7],
      dtype=int32)

In [64]:
np.argsort(X,axis=1)

array([[0, 1, 3, 2],
       [1, 0, 2, 3],
       [1, 3, 2, 0],
       [1, 0, 3, 2]], dtype=int32)

In [65]:
np.argsort(X,axis=0)

array([[0, 1, 1, 2],
       [3, 3, 2, 0],
       [1, 2, 0, 3],
       [2, 0, 3, 1]], dtype=int32)

In [66]:
X

array([[2, 5, 8, 6],
       [4, 0, 4, 8],
       [8, 2, 7, 4],
       [3, 1, 9, 6]])

In [67]:
np.argpartition(X,2,axis=1)

array([[0, 1, 3, 2],
       [1, 0, 2, 3],
       [1, 3, 2, 0],
       [1, 0, 3, 2]], dtype=int32)

In [69]:
np.partition(X,2)

array([[2, 5, 6, 8],
       [0, 4, 4, 8],
       [2, 4, 7, 8],
       [1, 3, 6, 9]])

In [70]:
np.argpartition(X,2,axis=0)

array([[0, 1, 1, 2],
       [3, 3, 2, 0],
       [1, 2, 0, 3],
       [2, 0, 3, 1]], dtype=int32)

In [72]:
np.partition(X,2,axis=0)

array([[2, 0, 4, 4],
       [3, 1, 7, 6],
       [4, 2, 8, 6],
       [8, 5, 9, 8]])