## numpy基础

In [17]:
import numpy

In [18]:
numpy.__version__

'1.15.0'

In [19]:
import numpy as np

In [20]:
np.__version__

'1.15.0'

## python list的特点

In [21]:
L=[i for i in range(10)]

In [22]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
L[5]

5

In [24]:
L[5]=19
L

[0, 1, 2, 3, 4, 19, 6, 7, 8, 9]

In [25]:
L[5]='hello world'
L

[0, 1, 2, 3, 4, 'hello world', 6, 7, 8, 9]

## array 限定数据类型

In [26]:
import array

In [27]:
arr=array.array('i',[i for i in range(10) ])

In [28]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5]

5

In [30]:
arr[5]=100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [31]:
arr[5]='hello'

TypeError: an integer is required (got type str)

## numpy.array 

In [ ]:
nparr=np.array([i for i in range(10)])

In [ ]:
nparr

In [ ]:
nparr[5]

In [ ]:
nparr[5]=100
nparr

In [ ]:
nparr[5]='hello'
nparr

In [ ]:
nparr.dtype

In [ ]:
nparr[5]=5.0
nparr

In [ ]:
nparr.dtype

In [ ]:
nparr[3]=3.1111
nparr

In [ ]:
nparr[3]=3.9
nparr

In [ ]:
nparr2=np.array([1,2,3.0])
nparr2.dtype

## numpy.array 的其他创建方法

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros(10).dtype

dtype('float64')

In [38]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [49]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
np.twos(10)

AttributeError: module 'numpy' has no attribute 'twos'

In [51]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
np.full(shape=(2,3),fill_value=666)

array([[666, 666, 666],
       [666, 666, 666]])

### range 和arange

In [56]:
[i for i in range(0,10,2)]

[0, 2, 4, 6, 8]

In [59]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [61]:
range(0,10,0.2)

TypeError: 'float' object cannot be interpreted as an integer

In [62]:
np.arange(0,10,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

### linspace

In [63]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

### random

In [64]:
np.random.random()

0.23166660242909864

In [84]:
np.random.randint(0,10)

8

In [87]:
np.random.randint(4,10,[5,3])

array([[7, 6, 9],
       [4, 6, 7],
       [7, 5, 5],
       [6, 6, 7],
       [9, 4, 9]])

In [88]:
np.random.randint(4,10,3)

array([8, 9, 7])

In [89]:
np.random.seed(1)

In [90]:
np.random.randint(4,10,3)

array([9, 7, 8])

In [91]:
np.random.seed(1)
np.random.randint(4,10,3)

array([9, 7, 8])

In [92]:
np.random.randint(4,10,3)

array([4, 5, 7])

In [94]:
np.random.normal(0,1,10)

array([-1.601721  , -1.47782957,  0.48349585,  0.18843661, -0.46468632,
        0.86182712, -2.65426198,  1.15226492,  0.19664341, -1.54521415])