## numpy.array 的合并 

In [2]:
import numpy as np

In [3]:
x=np.array([1,2,3])

In [4]:
y=np.array([3,2,1])

In [5]:
x

array([1, 2, 3])

In [6]:
y

array([3, 2, 1])

In [7]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [9]:
z=np.array([666,666,666])

In [13]:
A=np.array(([1,2,3],[4,5,6]))

In [15]:
A.ndim

2

In [16]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [17]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [30]:
z.reshape(-1,3)

array([[666, 666, 666]])

In [32]:
z.reshape(-1,3).ndim

2

In [31]:
np.concatenate([A,z.reshape(-1,3)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [33]:
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [36]:
B=np.full(shape=(2,2),fill_value=100)

In [37]:
B

array([[100, 100],
       [100, 100]])

In [38]:
np.concatenate([A,B],axis=1)

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [39]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [40]:
np.hstack(A,z)

TypeError: hstack() takes 1 positional argument but 2 were given

## 分割操作

In [46]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
x1,x2,x3=np.split(x,[3,7])

In [45]:
x1

array([0, 1, 2])

In [48]:
x2

array([3, 4, 5, 6])

In [49]:
x3

array([7, 8, 9])

In [50]:
x1,x2=np.split(x,[5])

In [51]:
x1

array([0, 1, 2, 3, 4])

In [52]:
x2

array([5, 6, 7, 8, 9])

In [54]:
A=np.arange(16).reshape([4,4])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
A1,A2=np.split(A,[2])

In [56]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [57]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
A1,A2=np.split(A,[2],axis=1)

In [59]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [60]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [61]:
upper,lower=np.vsplit(A,[2])

In [62]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [63]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
left,right=np.hsplit(A,[2])

In [65]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [66]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [69]:
data=np.arange(16).reshape([4,4])
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
X,y=np.hsplit(data,[-1])

In [72]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [73]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [77]:
y.ndim

2

In [85]:
y[:,0]

array([ 3,  7, 11, 15])