## 3.7 numpy 中的矩阵运算

In [1]:
n=10

In [2]:
L=[i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
L*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
%%timeit
A=[]
for e in L:
    A.append(2*e)
A

2.22 µs ± 250 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
%%timeit
A=[2*e for e in L]

1.63 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
import numpy as np
L=np.arange(n)

In [7]:
%%timeit
A=np.array(2*e for e in L)

4.13 µs ± 513 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
A

NameError: name 'A' is not defined

In [9]:
%%timeit
A=L*2
A

1.3 µs ± 65.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
A

NameError: name 'A' is not defined

## Universal function

In [12]:
x=np.arange(1,16).reshape((3,5))

In [13]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
x+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [15]:
x-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
x/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [17]:
x//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [18]:
x**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [19]:
x%2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [20]:
1/x

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [21]:
np.abs(x)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [22]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [23]:
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [24]:
np.power(3,x)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [25]:
np.log(x)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

##  矩阵运算

In [26]:
A=np.array(([1,2],[3,4]))
A

array([[1, 2],
       [3, 4]])

In [27]:
B=np.full(shape=(2,2),fill_value=10)
B

array([[10, 10],
       [10, 10]])

In [28]:
A+B

array([[11, 12],
       [13, 14]])

In [29]:
A-B

array([[-9, -8],
       [-7, -6]])

In [30]:
A*B

array([[10, 20],
       [30, 40]])

In [31]:
A/B

array([[0.1, 0.2],
       [0.3, 0.4]])

In [33]:
A.dot(B)

array([[30, 30],
       [70, 70]])

In [35]:
A.T

array([[1, 3],
       [2, 4]])

## 向量和矩阵的运算

In [36]:
v=np.array([1,2])

In [37]:
v+A

array([[2, 4],
       [4, 6]])

In [38]:
A

array([[1, 2],
       [3, 4]])

In [42]:
A.shape

(2, 2)

In [44]:
A.shape[0]

2

In [45]:
np.vstack([v]*A.shape[0])

array([[1, 2],
       [1, 2]])

In [46]:
np.vstack([v]*A.shape[0])+A

array([[2, 4],
       [4, 6]])

In [47]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [48]:
np.tile(v,(1,2))

array([[1, 2, 1, 2]])

In [49]:
v*A

array([[1, 4],
       [3, 8]])

In [51]:
v.dot(A)

array([ 7, 10])

In [52]:
A.dot(v)

array([ 5, 11])

## 矩阵的逆

In [53]:
A

array([[1, 2],
       [3, 4]])

In [54]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [55]:
invA=np.linalg.inv(A)

In [56]:
A.dot(invA)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [57]:
invA.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

In [60]:
X=np.arange(16).reshape(2,8)

In [61]:
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [62]:
np.linalg.inv(X)

LinAlgError: Last 2 dimensions of the array must be square

### 伪逆的矩阵

In [63]:
pinvX=np.linalg.pinv(X)

In [65]:
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -6.93889390e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [67]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.91433544e-16],
       [ 1.33226763e-15,  1.00000000e+00]])