In [1]:
import numpy as np

In [2]:
x=np.arange(16)

In [3]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
x[3]

3

In [5]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [6]:
x[3:9:2]

array([3, 5, 7])

In [7]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [8]:
ind=[3,5,8]

In [9]:
x[ind]

array([3, 5, 8])

In [14]:
ind=np.array([[0,2],
              [1,3]])

In [17]:
x[ind]

array([[0, 2],
       [1, 3]])

In [18]:
X=x.reshape(4,-1)

In [19]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
row=[0,1,2]

In [24]:
col=[1,2,3]

In [25]:
X[row,col]

array([ 1,  6, 11])

In [26]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [27]:
col=[True,False,True,True]

In [28]:
X[1:3,col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

In [29]:
col=[1,0,1,1]

In [30]:
X[1:3,col]

array([[5, 4, 5, 5],
       [9, 8, 9, 9]])

## numpy.array 的比较

In [35]:
x=np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [34]:
x>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [36]:
x<=3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [37]:
x>=3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [38]:
x==3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [39]:
x!=3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [41]:
2*x==24-4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [43]:
X=x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
X<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [46]:
np.sum(X<3)

3

In [49]:
np.count_nonzero(x<=3)

4

In [50]:
np.any(x==0)

True

In [51]:
np.any(x<0)

False

In [52]:
np.all(x>=0)

True

In [53]:
np.all(x>0)

False

In [54]:
np.sum(X%2==0)

8

In [55]:
np.sum(X%2==0,axis=1)

array([2, 2, 2, 2])

In [56]:
np.sum(X%2==0,axis=0)

array([4, 0, 4, 0])

In [58]:
np.sum((x<3)&(x<10))

3

In [59]:
np.sum((x<3)|(x<10))

10

In [63]:
np.sum(~(x==0))

15

In [65]:
X[X<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
X[X%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [ ]:
X[X[:,3]%3==0,:]