In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris=datasets.load_iris()

In [3]:
X=iris.data

In [4]:
y=iris.target

In [5]:
X[:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [8]:
X_train.shape

(112, 4)

In [9]:
y_train.shape

(112,)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
standardScaler=StandardScaler()

In [12]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [13]:
standardScaler.mean_

array([5.88392857, 3.01160714, 3.86339286, 1.24285714])

In [14]:
standardScaler.scale_ 

array([0.80905076, 0.43089308, 1.71953044, 0.74206689])

In [15]:
X_train[:10,:]

array([[7.6, 3. , 6.6, 2.1],
       [6.5, 3. , 5.5, 1.8],
       [5. , 3. , 1.6, 0.2],
       [6.9, 3.1, 5.4, 2.1],
       [5. , 2.3, 3.3, 1. ],
       [6.6, 3. , 4.4, 1.4],
       [6.7, 3.1, 4.4, 1.4],
       [6. , 2.2, 5. , 1.5],
       [4.3, 3. , 1.1, 0.1],
       [5. , 3.5, 1.3, 0.3]])

In [16]:
X_train=standardScaler.transform(X_train)

In [17]:
X_test_standard=standardScaler.transform(X_test)

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
knn_clf=KNeighborsClassifier()

In [20]:
knn_clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [21]:
knn_clf.score(X_test_standard,y_test)

1.0

In [22]:
knn_clf.score(X_test,y_test)

0.2631578947368421